# -*- coding: utf-8 -*-
import glob
import os
import time
try:
    from lib import color, human_readable_size, say
except ImportError as e:
    raise e


today = "%4d%02d%02d" % time.localtime()[:3]
logpath = os.path.join(os.environ.get('HOME'), today)
if not os.path.isdir(logpath):
    os.makedirs(logpath)


def get_log_file(suffix):
    """Determine screen logging file name.
    It's really long, so split out."""
    day_and_time = "%4d%02d%02d-%02d%02d%02d" % time.localtime()[:-3]
    username = os.getlogin()
    filename = '-'.join([day_and_time, username, suffix])
    f = os.path.join(logpath, filename)
    return f


def do_list():
    """eg: log list
    """
    files = sorted(glob.glob(logpath + "/*"))
    if files:
        print("Log files in %s:" % str(logpath))
        print("%s Size  -  Date  - Time - User - CMD - Host%s" %
              (color.WHITE, color.OFF))
        for f in files:
            print("%s\t%s" % (human_readable_size(os.path.getsize(f)),
                              str(os.path.basename(f))))
    else:
        print("You don't have any log file.")


def do_view(f):
    """View logged screen file.
    eg: log view 20130705-110150-mj-telnet-10.0.0.1
    """
    # TODO: rewrite with pure python. Try to strip Control Code generated by
    # TUI, or record time info and rewind them.
    f = os.path.join(logpath, f)
    if os.path.isfile(f):
        os.system("less -r %s" % f)
    else:
        say.nofile(f, prefix="log view")
        return False
